issueOpened: 'Issue Opened! Executed from config.yml'
prOpened: 'Pull Request Opened! Executed from config.yml'

jobs:
  - targetBranch: main
    jenkinsUrl: 'http://51.20.3.203:8080/job/ccif_build_pipeline/'
    triggers:
      pull_request:
        labels:
          - check
          - merge
