branches:
  - target: master
    jobs:
      - job:
          url: http://13.48.136.179:8080/job/Pull_and_merge
        triggers:
          - pull_request:
              labels:
                - check
          - pull_request:
              require:
                review: true
              labels:
                - merge
