issueOpened: 'Issue Opened! Executed from config.yml'
prOpened: 'Pull Request Opened! Executed from config.yml'

jobs:
  - targetBranch: main
    jenkinsUrl: 'https://a177-223-233-84-210.ngrok-free.app/job/Development/job/check/'
    triggers:
      pull_request:
        labels:
          - Check
          - Merge
  - targetBranch: release
    jenkinsUrl: 'https://a177-223-233-84-210.ngrok-free.app/job/Development/job/check/'
    triggers:
      pull_request:
        labels:
          - Check
          - Merge 
