issueOpened: 'Issue Opened! Executed from config.yml'
prOpened: 'Pull Request Opened! Executed from config.yml'

jobs:
  - targetBranch: main
      - job:
          url: http://16.171.25.6:8080/job/ccif_build_pipeline/
        triggers:
          - pull_request:
              labels:
                - check
          - pull_request:
              require:
                review: true
              labels:
                - merge
