issueOpened: 'Issue Opened! Executed from config.yml'
prOpened: 'Pull Request Opened! Executed from config.yml'

jobs:
  - targetBranch: main
    jenkinsUrl: 'http://16.171.198.76:8080/job/ccif_build_pipeline/'
    triggers:
      pull_request:
        labels:
          - Check
          - Merge
