name: c

on:
  pull_request:
    types:
      - opened

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16

      - name: Install Dependencies
        run: npm install @actions/github @octokit/rest

      - name: Add Default Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node -e "const fs = require('fs');
                    const fetch = require('node-fetch');
                    const { Octokit } = require('@octokit/rest');
                    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN, request: { fetch }});

                    const eventPayload = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
                    const comment = 'Jenkinks Job is triggered for this Pull request Check at: http://16.171.34.1:8080/job/jenkins_Pull_request%20_new/';

                    const owner = eventPayload.repository.owner.login;  // Owner login
                    const repo = eventPayload.repository.name;  // Repository name
                    const issue_number = eventPayload.number;  // Issue/PR number
                    octokit.issues.createComment({ owner, repo, issue_number, body: comment });"
