name: GitHub Script

on:
  push:
    branches:
      - main

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GitHub Script
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.repos.createDispatchEvent({
              owner: 'Md-Fayazz',
              repo: 'Demo',
              event_type: 'trigger-jenkins-job'
            })



