name: Create GitHub Release on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged into release branch
        id: check_merged_into_release
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
        run: echo "PR is merged into release branch"

      - name: Checkout code
        uses: actions/checkout@v2.4.4  
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0  
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

