name: Create GitHub Release on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged into release branch
        id: check_merged_into_release
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
        run: echo "PR is merged into release branch"

      - name: Get latest tag
        if: steps.check_merged_into_release.outputs.result
        id: get_latest_tag
        run: |
          echo "Running get latest tag step"
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "Latest tag is: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Create GitHub Release
        if: steps.check_merged_into_release.outputs.result
        id: create_release
        uses: actions/create-release@v1
        with:
          files: |
            ./*  # Include all files in the release
          name: Release ${{ steps.get_latest_tag.outputs.tag }}
          tag_name: ${{ steps.get_latest_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
