name: Trigger Jenkins Job on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Label
        id: check_label
        run: echo ::set-output name=label::${{ github.event.label.name }}

      - name: Trigger Jenkins Job
        if: steps.check_label.outputs.label == 'Check'
        run: |
          JENKINS_USERNAME=${{ secrets.JENKINS_USERNAME }}
          JENKINS_TOKEN=${{ secrets.JENKINS_API_TOKEN }}
          JOB_URL="http://51.20.12.98:8080/job/Pull_and_merge/buildWithParameters?REPO_NAME=${{ github.repository }}&PR_NUMBER=${{ github.event.pull_request.number }}"
          curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN $JOB_URL
          BUILD_NUMBER=$(curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN http://51.20.12.98:8080/job/Pull_and_merge | jq -r '.number')
          echo "The Jenkins build number is $BUILD_NUMBER"
          echo "::set-output name=build_number::$BUILD_NUMBER"
      - name: Check Jenkins Build Status
        id: check_build_status
        run: |
          JENKINS_USERNAME=${{ secrets.JENKINS_USERNAME }}
          JENKINS_TOKEN=${{ secrets.JENKINS_API_TOKEN }}
          BUILD_STATUS=$(curl -X GET -u $JENKINS_USERNAME:$JENKINS_TOKEN "http://51.20.12.98:8080/job/Pull_and_merge/$BUILD_NUMBER/api/json" | jq -r '.result')
          echo "Jenkins Build Status: $BUILD_STATUS"
          if [[ "$BUILD_STATUS" == "SUCCESS" ]]; then
            echo "::set-output name=build_result::success"
          else
            echo "::set-output name=build_result::failure"
          fi

      - name: Set GitHub Check Status
        id: set_check_status
        if: steps.check_label.outputs.label == 'Check'
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          BUILD_RESULT=${{ steps.check_build_status.outputs.build_result }}
          if [[ "$BUILD_RESULT" == "success" ]]; then
            CHECK_STATUS="completed"
            CHECK_CONCLUSION="success"
            CHECK_SUMMARY="Jenkins build succeeded"
          else
            CHECK_STATUS="completed"
            CHECK_CONCLUSION="failure"
            CHECK_SUMMARY="Jenkins build failed"
          fi
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.antiope-preview+json" \
            -d "{
              \"state\": \"$CHECK_STATUS\",
              \"context\": \"Jenkins Build\",
              \"description\": \"$CHECK_SUMMARY\",
              \"target_url\": \"$JOB_URL\",
              \"conclusion\": \"$CHECK_CONCLUSION\"
            }" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs"
          
