name: Trigger Jenkins Job on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Label
        id: check_label
        run: echo "LABEL=${{ github.event.label.name }}" >> $GITHUB_ENV

      - name: Trigger Jenkins Job
        if: env.LABEL == 'Check'
        run: |
          JENKINS_USERNAME=${{ secrets.JENKINS_USERNAME }}
          JENKINS_TOKEN=${{ secrets.JENKINS_API_TOKEN }}
          JOB_URL="http://16.170.212.178:8080/job/Pull_and_merge/buildWithParameters?REPO_NAME=${{ github.repository }}&PR_NUMBER=${{ github.event.pull_request.number }}"
          curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN $JOB_URL

      - name: Wait for Jenkins Build
        id: wait_for_build
        run: |
          JENKINS_USERNAME=${{ secrets.JENKINS_USERNAME }}
          JENKINS_TOKEN=${{ secrets.JENKINS_API_TOKEN }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          while :; do
            # Use Jenkins API to find the build number for the matching PR number
            BUILD_NUMBER=$(curl -X GET -u $JENKINS_USERNAME:$JENKINS_TOKEN "http://16.170.212.178:8080/job/Pull_and_merge/api/json" | jq -r ".builds[] | select(.actions[].parameters[].value == 'PR_NUMBER=${PR_NUMBER}') | .number")
            
            if [[ -n "$BUILD_NUMBER" ]]; then
              BUILD_STATUS=$(curl -X GET -u $JENKINS_USERNAME:$JENKINS_TOKEN "http://16.170.212.178:8080/job/Pull_and_merge/$BUILD_NUMBER/api/json" | jq -r '.result')
              if [[ "$BUILD_STATUS" == "SUCCESS" ]]; then
                echo "Jenkins Build Status: $BUILD_STATUS"
                echo "BUILD_RESULT=success" >> $GITHUB_ENV
                break
              elif [[ "$BUILD_STATUS" == "FAILURE" ]]; then
                echo "Jenkins Build Status: $BUILD_STATUS"
                echo "BUILD_RESULT=failure" >> $GITHUB_ENV
                break
              fi
            fi
            
            echo "Waiting for Jenkins build to complete..."
            sleep 30  # Adjust the sleep interval as needed
          done

      - name: Set GitHub Check Status
        if: env.LABEL == 'Check'
        run: |
          GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          BUILD_RESULT=${{ env.BUILD_RESULT }}
          if [[ "$BUILD_RESULT" == "success" ]]; then
            CHECK_STATUS="completed"
            CHECK_CONCLUSION="success"
            CHECK_SUMMARY="Jenkins build succeeded"
          else
            CHECK_STATUS="completed"
            CHECK_CONCLUSION="failure"
            CHECK_SUMMARY="Jenkins build failed"
          fi
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.antiope-preview+json" \
            -d "{
              \"state\": \"$CHECK_STATUS\",
              \"context\": \"Jenkins Build\",
              \"description\": \"$CHECK_SUMMARY\",
              \"target_url\": \"$JOB_URL\",
              \"conclusion\": \"$CHECK_CONCLUSION\"
            }" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs"
