name: Trigger Jenkins Job on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Label
        id: check_label
        run: echo ::set-output name=label::${{ github.event.label.name }}

      - name: Trigger Jenkins Job
        if: steps.check_label.outputs.label == 'your_desired_label'
        run: |
          # Replace with your Jenkins job URL and credentials if needed
          JENKINS_JOB_URL="https://your-jenkins-server/job/your-job-name/build"
          JENKINS_USERNAME="your-username"
          JENKINS_TOKEN="your-token"

          curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN $JENKINS_JOB_URL
